### ISSUE TITLE
Possibility to include HTML content in the chat message

### ISSUE THREAD

**Issue by agustinbanuswork** [FlowingCode/ChatAssistant#32]
### Feature proposal

I would like to know if a chat message can be configured in order to include html content such as a link ?. Because, currently, I am only able to display plaint text content... If not, I am willing to make the necessary changes...

**Comment by mlopezFC** [comment]
Hi @agustinbanuswork !
[It already supports markdown](https://addonsv24.flowingcode.com/chat-assistant/markdown-demo), take a look:

![image](https://github.com/user-attachments/assets/72259a16-3af6-4a17-9d47-c78746a030f5)

Is that enough for your needs?

**Comment by agustinbanuswork** [comment]
Thank you for answering... Here is my problem...
I have the following code:
`this.chatAssistant = new ChatAssistant(true);`
Then I am doing:
`this.chatAssistant.sendMessage(---)`
But nothing is rendered... Do you know what could be the reason ?... Yes... Its indeed helpful but for some reason it appears on blank; not the same situation as if initiliza de assistant with false...

**Comment by agustinbanuswork** [comment]
I have another concern... Do you know why the component rendered isnt executed ? Here is the code I am referring to...
![image](https://github.com/user-attachments/assets/cd7960bf-9864-4cff-a185-9a34a46a2c3b)

**Comment by mlopezFC** [comment]
Did you add `com.flowingcode` to the `vaadin.whitelisted-packages` property in `src/main/resources/application.properties` as explained in [the Developer Guide section of the documentation](https://github.com/FlowingCode/ChatAssistant?tab=readme-ov-file#special-configuration-when-using-spring)?

**Comment by agustinbanuswork** [comment]
No... But I have just added like below:
![image](https://github.com/user-attachments/assets/671fe3fb-3cf8-4abc-8b44-8e656e74f68c)
And seems it doesnt work still...
![image](https://github.com/user-attachments/assets/656e9451-9401-4b1e-bef4-7ca8496b7136)

**Comment by mlopezFC** [comment]
Sorry, now I realize that the guide is outdated, the correct property is allowed-packages, try adding com.flowingcode to that property.

**Comment by agustinbanuswork** [comment]
It worked Bro ! thanks ! Do you speak spanish ? Muchas gracias !. just another thing... Could I set the width ? or make it inline ?... THnkax you so much.,..

**Comment by mlopezFC** [comment]
Sii! .. hablo español!! ... [creé un issue hace un tiempo](https://github.com/FlowingCode/ChatAssistant/issues/18) para agregar esa característica, pero este componente está basado en [este otro](https://github.com/yishiashia/wc-chatbot/), así que [les creé un issue a ellos](https://github.com/yishiashia/wc-chatbot/issues/4) para ver si lo implementan. 
Si no lo hacen estoy pensando en reescribir este totalmente y hacerlo con los componentes que provee Vaadin. Espero que te sirva!

**Comment by agustinbanuswork** [comment]
I am asking you this as there is some output from a chatgpt that is not rendered ok... I assume setting a higher width may solve it...

**Comment by agustinbanuswork** [comment]
Si... Ni hablar... Me re sirve... Lo que estoy haciendo es integrar langchain4j y rag... Entonces lo que me devuelve openai es una lista pero no se ve bien... Igual es un detslle menor... Es solucionable...

Tenes otros componentes vaadin en el repo ?

**Comment by mlopezFC** [comment]
[Somos los que más add-ons de Vaadin tenemos publicados en el directorio](https://vaadin.com/directory/?q=author%3AFlowing+Code) 😉 ... todas las demos están accesibles acá: https://addonsv24.flowingcode.com/

**Comment by mlopezFC** [comment]
Cierro el issue, pero cualquier duda lo vuelves a abrir o creas otro!
Saludos!
