### ISSUE TITLE
Add-on overlaps source in demo

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/ChatAssistant#4]
I can't read the sources because the chatbot is displayed on top of them.
![image](https://github.com/FlowingCode/ChatAssistant/assets/11554739/cbbc6691-c9dd-4dfe-a2a0-2f8cf5a9504d)

**Comment by javier-godoy** [comment]
We'll address this by https://github.com/FlowingCode/CommonsDemo/issues/72

**Comment by mlopezFC** [comment]
Okey, but also take into account that you can minimize the chat window so you can see the underlying code if it is needed. I thought about implementing a feature to choose the location of the chatbot but it is not easy and maybe too much effort just to see the code while it is not minimized so I disregarded it.
