### ISSUE TITLE
Sender class is package private

### ISSUE THREAD

**Issue by ruizrube** [FlowingCode/ChatAssistant#5]
Hi. 
Thanks for this component.

I am unable to create an instance of the Sender class in order to send a message. 

Regards

**Comment by javier-godoy** [comment]
Hello. The `Sender` class is public. https://github.com/FlowingCode/ChatAssistant/blob/e6375acc782c0223735aef49fda75e3f809dfe21/src/main/java/com/flowingcode/vaadin/addons/chatassistant/Sender.java#L44

Can you please attach a code snippet?

**Comment by ruizrube** [comment]
Attach image with the decompiled code
<img width="1604" alt="Screenshot 2023-11-11 at 13 49 37" src="https://github.com/FlowingCode/ChatAssistant/assets/790837/34e4b44c-171d-444a-ada9-9646619a86de">

**Comment by javier-godoy** [comment]
`Sender` and `Message` classes have builders, so you can do: 
```
Sender.builder().name("Assistant").id("1").avatar("chatbot.png").build();
```

I'll keep this issue open because the examples use the constructor instead of the builder.

**Comment by ruizrube** [comment]
Thank you
